/**
 * Drizzle schema for the `inquiries` table (Story 3.3, Decision 2).
 *
 * Naming conventions (architecture.md §Naming Patterns):
 *   - Table:   snake_case, plural  → `inquiries`
 *   - Columns: snake_case          → `created_at`, `mail_status`, …
 *   - TS props: camelCase (Drizzle bridge) → `createdAt`, `mailStatus`, …
 *
 * The casing boundary lives ENTIRELY inside this file — JSON emitted from the
 * route handler is camelCase; snake_case never leaks to the client.
 *
 * DB-side defaults are used for `id` (gen_random_uuid()) and timestamps
 * (now()) — no `new Date()` in app code (architecture determinism rule).
 */
import { pgTable, text, timestamp, uuid } from 'drizzle-orm/pg-core';

export const inquiries = pgTable('inquiries', {
  /** Non-enumerable UUID PK — generated by Postgres (gen_random_uuid()). */
  id: uuid('id').primaryKey().defaultRandom(),

  /** Creation timestamp — UTC, set by Postgres at insert (now()). */
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),

  /** Last-update timestamp — UTC, set by Postgres at insert; updated manually on status changes. */
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),

  /** Submitter's name — required text field. */
  name: text('name').notNull(),

  /** Submitter's email — required text field. */
  email: text('email').notNull(),

  /** Submitter's organisation — optional. */
  org: text('org'),

  /** Inquiry message body — required text field. */
  message: text('message').notNull(),

  /** Talk topic / interest — optional. */
  topic: text('topic'),

  /** How the submitter heard about Josh — required (the "attribution" how-heard field). */
  attribution: text('attribution').notNull(),

  /**
   * Inquiry source: 'form' (web Invite-Me form) | 'agent' (Stage-3 FR-12 path).
   * Defaults to 'form'.
   */
  source: text('source').notNull().default('form'),

  /**
   * Workflow status: 'new' | 'replied'.
   * Defaults to 'new'.
   */
  status: text('status').notNull().default('new'),

  /**
   * Email notification status: 'sent' | 'failed' | 'skipped'.
   * Set after the email attempt (or 'skipped' when RESEND_API_KEY is unset).
   * null on initial insert (before the email step).
   */
  mailStatus: text('mail_status'),
});

export type Inquiry = typeof inquiries.$inferSelect;
export type NewInquiry = typeof inquiries.$inferInsert;
