/**
 * retriever.ts — KB retriever seam (Story 4.1).
 *
 * Loads the serialized KB corpus (`api/data/kb-index.json`, built by
 * `scripts/build-kb-index.ts`) into an in-memory Orama v3 full-text index and
 * exposes an async `search(query, k)` for the Guide (Story 4.3).
 *
 * SEAM ISOLATION: `@orama/orama` is imported ONLY here — no other module in the
 * codebase imports it directly. The Guide (4.3) calls `search()` only, so a
 * future lexical→hybrid/pgvector swap is local to this file (architecture
 * §Retriever abstraction).
 *
 * KNOWLEDGE HORIZON: the Guide's knowledge is "fresh as of the last build."
 * The index is not "never stale" — it is regenerated by `pnpm build` each
 * deploy. To update the Guide's knowledge, edit `content/kb/` and rebuild.
 *
 * BOOTSTRAP PLACEMENT: eager `loadIndex()` is called from `api/src/index.ts`
 * (the bootstrap), NOT from `app.ts`. Importing `app.ts` in tests MUST NOT
 * open any file or trigger index load (Story 3.0 import-side-effect lesson).
 * `loadIndex()` is idempotent — the bootstrap's eager call and a test's
 * direct call share one in-memory index.
 *
 * DETERMINISM: the corpus is our own deterministic JSON (explicit stable chunk
 * IDs, sorted enumeration). We `create` + `insertMultiple` with those explicit
 * IDs so Orama never generates a random ID. See Decision 4 in the story file.
 */
import { existsSync, readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { create, insertMultiple, search as oramaSearch } from '@orama/orama';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/** A chunk from the KB corpus — the retrieval unit for the Guide. */
export interface RetrievedChunk {
  /** Stable chunk ID (e.g. `about#bio`). */
  id: string;
  /** Citation route on the Static Mirror (e.g. `/about/`). */
  route: string;
  /** Human label for the citation (e.g. `About Joshua`). */
  label: string;
  /** The section heading for this chunk. */
  heading: string;
  /** The chunk prose. */
  text: string;
  /** BM25 relevance score from Orama. Higher is more relevant. */
  score: number;
}

/** The Orama schema for a KB chunk document. */
interface KbChunkDoc {
  id: string;
  route: string;
  label: string;
  heading: string;
  text: string;
}

// ---------------------------------------------------------------------------
// Module-level cached index (idempotent, loaded once)
// ---------------------------------------------------------------------------

// eslint-disable-next-line @typescript-eslint/no-explicit-any
let _db: any = null;

/**
 * Resolve the KB index path.
 * Defaults to `api/data/kb-index.json` relative to the module's location
 * (api/src/lib/ → ../../data/kb-index.json = api/data/kb-index.json).
 */
function defaultIndexPath(): string {
  const thisFile = fileURLToPath(import.meta.url);
  return resolve(dirname(thisFile), '..', '..', 'data', 'kb-index.json');
}

/**
 * Load (or return the already-loaded) Orama in-memory index.
 *
 * Idempotent — safe to call multiple times; the index is built once and cached.
 * Called eagerly from `api/src/index.ts` at bootstrap so the first search
 * request is not penalized by load latency.
 *
 * Fails loud if the index file is missing — it is a build artifact; absence
 * means `pnpm build` was not run.
 *
 * @param indexPath  Optional override for the corpus JSON path (for tests).
 */
export async function loadIndex(indexPath?: string): Promise<void> {
  if (_db !== null) return; // already loaded — idempotent

  const path = indexPath ?? defaultIndexPath();

  if (!existsSync(path)) {
    throw new Error(
      `[retriever] KB index not found at "${path}". ` +
        `Run "pnpm build" (or "pnpm build:content") to generate it. ` +
        `The index is a build artifact — it is not committed to the repository.`,
    );
  }

  const raw = readFileSync(path, 'utf8');
  let corpus: KbChunkDoc[];
  try {
    corpus = JSON.parse(raw) as KbChunkDoc[];
  } catch (cause) {
    throw new Error(`[retriever] KB index at "${path}" is not valid JSON.`, { cause });
  }

  // Create the Orama v3 in-memory index with an explicit schema.
  // BM25 is the v3 default full-text algorithm; English tokenizer is built-in.
  const db = await create<{
    id: 'string';
    route: 'string';
    label: 'string';
    heading: 'string';
    text: 'string';
  }>({
    schema: {
      id: 'string',
      route: 'string',
      label: 'string',
      heading: 'string',
      text: 'string',
    },
  });

  // Insert corpus with explicit IDs in sorted order (as in the corpus file).
  // This ensures Orama never generates a random ID — deterministic by construction.
  await insertMultiple(db, corpus);

  _db = db;
}

/**
 * Reset the cached index (for tests only — not exported in production usage).
 * Allows tests to call `loadIndex(customPath)` without fighting the module cache.
 */
export function _resetIndex(): void {
  _db = null;
}

// ---------------------------------------------------------------------------
// search()
// ---------------------------------------------------------------------------

/**
 * Default number of top-k results to return.
 * 3–6 per architecture §Retriever abstraction.
 */
export const DEFAULT_K = 5;

/**
 * Search the KB index for chunks relevant to `query` using BM25 full-text search.
 *
 * Must be called after `loadIndex()` resolves. If the index is not loaded,
 * throws — callers should ensure `loadIndex()` is awaited at bootstrap.
 *
 * @param query  The search query string (e.g. a user question or keyword).
 * @param k      Max number of results to return (default: DEFAULT_K = 5).
 * @returns      Top-k RetrievedChunks ranked by BM25 score descending.
 *               Returns an empty array for below-threshold / zero-match queries.
 */
export async function search(query: string, k = DEFAULT_K): Promise<RetrievedChunk[]> {
  if (_db === null) {
    throw new Error(
      '[retriever] Index not loaded. Call loadIndex() before search(). ' +
        'The eager loadIndex() should have been called at bootstrap (api/src/index.ts).',
    );
  }

  const results = await oramaSearch(_db, {
    term: query,
    limit: k,
    mode: 'fulltext',
  });

  // Map Orama hits to RetrievedChunk shape
  return results.hits.map((hit) => {
    const doc = hit.document as KbChunkDoc;
    return {
      id: doc.id,
      route: doc.route,
      label: doc.label,
      heading: doc.heading,
      text: doc.text,
      score: hit.score,
    };
  });
}
