/**
 * build-kb-index.ts — deterministic KB index generator (Story 4.1).
 *
 * Reads the curated `content/kb/*.md` set (sorted, default-deny — never
 * `_bmad-output/` or any other path), strips frontmatter via the Story-4.0
 * `stripFrontmatter` helper, chunks each doc at heading boundaries (~300–800
 * tokens), and writes a deterministic serialized corpus to
 * `api/data/kb-index.json` (gitignored).
 *
 * KNOWLEDGE HORIZON: the Guide's knowledge is "fresh as of the last build."
 * The index is not "never stale" — it is regenerated by `pnpm build` each
 * deploy. To update the Guide's knowledge, edit `content/kb/` and rebuild.
 *
 * HARD CONSTRAINTS (Story 1.8 / FR-33 / NFR-6):
 *  - NO network IO. No fetch, no HTTP.
 *  - DETERMINISTIC: no Date.now() / Math.random() / argless new Date().
 *    Files enumerated in sorted order (byCodeUnit); chunk IDs are explicit
 *    stable slugs. Same content → byte-identical output.
 *  - DEFAULT-DENY: reads ONLY `content/kb/*.md` (sorted glob) — never
 *    `_bmad-output/`, never a filesystem crawl.
 *  - FAIL LOUD: throws on any unreadable file (never silently skips).
 *
 * Orama determinism note: Orama v3 generates random IDs when documents have
 * no explicit `id`. We therefore serialize OUR OWN sorted chunk corpus with
 * explicit stable IDs and rebuild the Orama index at load via `create` +
 * `insertMultiple` (Decision 4). This file is NOT Orama's internal engine
 * state — it is our deterministic corpus that Orama re-indexes at startup.
 */
import { mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { basename, dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { stripFrontmatter } from './lib/markdown.ts';
import type { Generator } from './build-content.ts';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/** Frontmatter fields required in every KB doc. */
export interface KbFrontmatter {
  route: string;
  label: string;
  title: string;
}

/** A single KB chunk — the unit of retrieval. */
export interface KbChunk {
  /** Explicit stable id: `${docSlug}#${headingSlug or chunkIndex}`. */
  id: string;
  /** Citation target on the Static Mirror (from frontmatter `route`). */
  route: string;
  /** Human label for the citation (from frontmatter `label`). */
  label: string;
  /** The heading text for this chunk (empty string for the preamble chunk). */
  heading: string;
  /** The chunk prose. */
  text: string;
}

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

/**
 * Locale-independent, fully-deterministic string comparator (NFR-6).
 * Mirrors the `byCodeUnit` from render-glassbox.ts — kept local so this
 * module has no import coupling to render-glassbox.
 */
function byCodeUnit(a: string, b: string): number {
  return a < b ? -1 : a > b ? 1 : 0;
}

/**
 * Convert a string to a URL-safe slug: lowercase, non-alphanum → hyphens,
 * collapse consecutive hyphens, trim leading/trailing hyphens.
 */
export function slugify(s: string): string {
  return s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

/**
 * Parse YAML frontmatter from a Markdown string.
 *
 * Returns the key/value pairs from the leading `---` block, or null if
 * no valid frontmatter is found. This is intentionally minimal — only
 * handles the flat string key-value shape the KB docs use.
 *
 * @param md  Raw markdown (with frontmatter if present).
 */
export function parseFrontmatter(md: string): KbFrontmatter | null {
  const match = md.match(/^---\r?\n(?=[a-zA-Z_][\w-]*\s*:(?:\s|$))([\s\S]*?)\r?\n---\r?\n?/);
  if (!match) return null;
  const block = match[1]!;
  const result: Record<string, string> = {};
  for (const line of block.split(/\r?\n/)) {
    const kv = line.match(/^([a-zA-Z_][\w-]*)\s*:\s*(.*)/);
    if (kv) result[kv[1]!] = kv[2]!.trim();
  }
  if (!result['route'] || !result['label'] || !result['title']) return null;
  return { route: result['route']!, label: result['label']!, title: result['title']! };
}

/**
 * Approximate token count. We use a simple word/punctuation split as a
 * fast proxy (1 token ≈ 0.75 words for BPE, but for BM25 lexical search
 * the actual token boundary is character-level; the ~300–800 window just
 * prevents over-long chunks from diluting relevance).
 */
function approxTokens(text: string): number {
  // Split on whitespace/punctuation runs; count non-empty segments
  return text.trim().split(/\s+/).filter(Boolean).length;
}

/**
 * Split a heading's prose if it exceeds ~800 tokens by newline/paragraph
 * boundaries, or merge it into its successor if it is under ~30 tokens.
 * Returns the split paragraphs as separate text strings (each still
 * attributed to the same heading).
 */
function splitOrMerge(sections: Array<{ heading: string; text: string }>): Array<{
  heading: string;
  text: string;
}> {
  const MAX_TOKENS = 800;
  // Only merge a section if it has no text at all (avoids swallowing real content).
  // The heading boundary chunker already filters out empty preambles, so this
  // primarily catches degenerate edge cases.
  const MIN_TOKENS = 1;
  const result: Array<{ heading: string; text: string }> = [];

  for (let i = 0; i < sections.length; i++) {
    const sec = sections[i]!;
    const tokens = approxTokens(sec.text);

    if (tokens > MAX_TOKENS) {
      // Split at paragraph breaks, accumulating up to MAX_TOKENS per chunk.
      const paras = sec.text.split(/\n\n+/);
      let buf = '';
      for (const para of paras) {
        const candidate = buf ? `${buf}\n\n${para}` : para;
        if (approxTokens(candidate) > MAX_TOKENS && buf) {
          // Flush the current buffer as a sub-chunk
          result.push({ heading: sec.heading, text: buf });
          buf = para;
        } else {
          buf = candidate;
        }
      }
      if (buf) {
        result.push({ heading: sec.heading, text: buf });
      }
    } else if (tokens < MIN_TOKENS && i + 1 < sections.length) {
      // Merge into the next section
      const next = sections[i + 1]!;
      sections[i + 1] = {
        heading: next.heading,
        text: sec.text + '\n\n' + next.text,
      };
      // Don't push this section; it's been merged
    } else {
      result.push(sec);
    }
  }

  return result;
}

/**
 * Chunk a KB doc's body at heading boundaries.
 *
 * A chunk = a heading + its prose up to the next heading of same-or-higher
 * level. The preamble (text before the first heading) is included as chunk 0
 * if non-empty.
 *
 * Heading detection: lines matching `^#{1,6}\s+(.+)$`.
 *
 * @param body     The doc body after frontmatter has been stripped.
 * @param docSlug  The stable doc slug for building chunk IDs.
 * @param fm       The parsed frontmatter (route, label).
 */
export function chunkDoc(body: string, docSlug: string, fm: KbFrontmatter): KbChunk[] {
  const lines = body.split(/\r?\n/);
  const sections: Array<{ heading: string; text: string }> = [];

  let currentHeading = '';
  let currentLines: string[] = [];

  for (const line of lines) {
    const headingMatch = line.match(/^#{1,6}\s+(.+)$/);
    if (headingMatch) {
      const prose = currentLines.join('\n').trim();
      if (prose) {
        sections.push({ heading: currentHeading, text: prose });
      }
      currentHeading = headingMatch[1]!.trim();
      currentLines = [];
    } else {
      currentLines.push(line);
    }
  }

  // Final section
  const finalProse = currentLines.join('\n').trim();
  if (finalProse) {
    sections.push({ heading: currentHeading, text: finalProse });
  }

  // Apply split/merge heuristic
  const processed = splitOrMerge(sections);

  // Assign stable IDs.
  // Track used heading slugs to disambiguate duplicates.
  const usedSlugs = new Map<string, number>();

  return processed.map((sec, idx): KbChunk => {
    const headingSlug = sec.heading ? slugify(sec.heading) : `chunk-${idx}`;
    const count = usedSlugs.get(headingSlug) ?? 0;
    usedSlugs.set(headingSlug, count + 1);
    const finalSlug = count === 0 ? headingSlug : `${headingSlug}-${count}`;
    const id = `${docSlug}#${finalSlug}`;
    return {
      id,
      route: fm.route,
      label: fm.label,
      heading: sec.heading,
      text: sec.text,
    };
  });
}

// ---------------------------------------------------------------------------
// Core build function (pure — exported for tests)
// ---------------------------------------------------------------------------

/**
 * Build the KB chunk corpus from a set of KB docs.
 *
 * @param kbDir     Absolute path to `content/kb/`.
 * @returns         Sorted array of KbChunks.
 */
export function buildKbCorpus(kbDir: string): KbChunk[] {
  // DEFAULT-DENY: enumerate ONLY content/kb/*.md in sorted order.
  // Never read _bmad-output/ or any other path.
  const files = readdirSync(kbDir)
    .filter((f) => f.endsWith('.md') && f !== 'README.md')
    .sort(byCodeUnit);

  const allChunks: KbChunk[] = [];

  for (const filename of files) {
    const absPath = join(kbDir, filename);
    let raw: string;
    try {
      raw = readFileSync(absPath, 'utf8');
    } catch (cause) {
      throw new Error(
        `[build-kb-index] FAIL — cannot read KB doc: "${filename}" (path: "${absPath}"). ` +
          `Ensure the file exists and is readable.`,
        { cause },
      );
    }

    const fm = parseFrontmatter(raw);
    if (!fm) {
      throw new Error(
        `[build-kb-index] FAIL — missing or invalid frontmatter in: "${filename}". ` +
          `Each KB doc must have "route", "label", and "title" in YAML frontmatter.`,
      );
    }

    // Strip frontmatter via the Story-4.0 hardened helper (reuse, do not re-implement).
    const body = stripFrontmatter(raw);

    const docSlug = basename(filename, '.md');
    const chunks = chunkDoc(body, docSlug, fm);
    allChunks.push(...chunks);
  }

  // Corpus is already in docSlug order (files sorted) + chunk order within each doc.
  // No additional sort needed — deterministic by construction.
  return allChunks;
}

// ---------------------------------------------------------------------------
// Generator (registered in build-content.ts CONTENT_GENERATORS)
// ---------------------------------------------------------------------------

/**
 * The repo root is one level up from `scripts/`.
 * Mirrors `getRepoRoot()` in render-glassbox.ts.
 */
function getRepoRoot(): string {
  const scriptsDir = dirname(fileURLToPath(import.meta.url));
  return resolve(scriptsDir, '..');
}

/**
 * The Generator registered into CONTENT_GENERATORS.
 * Reads `content/kb/*.md` → chunks → writes `api/data/kb-index.json`.
 */
export const buildKbIndexGenerator: Generator = {
  name: 'build-kb-index',
  async run(): Promise<void> {
    const repoRoot = getRepoRoot();
    const kbDir = join(repoRoot, 'content', 'kb');
    const outputPath = join(repoRoot, 'api', 'data', 'kb-index.json');

    // Ensure the output directory exists.
    mkdirSync(dirname(outputPath), { recursive: true });

    const chunks = buildKbCorpus(kbDir);

    // Deterministic JSON write: stable key order, 2-space indent, trailing newline.
    // Mirrors `JSON.stringify(_, null, 2) + '\n'` pattern from render-glassbox.ts.
    writeFileSync(outputPath, JSON.stringify(chunks, null, 2) + '\n', 'utf8');

    console.log(`[build-kb-index] wrote ${chunks.length} chunk(s) to api/data/kb-index.json`);
  },
};
