/**
 * build-content.ts — the build-time CONTENT-PIPELINE ORCHESTRATOR (Story 1.8).
 *
 * WHAT THIS IS
 * ------------
 * The single entry point `pnpm build` runs BEFORE `astro build`. It executes an
 * ORDERED registry of content "generators", each of which reads ONLY from
 * `content/` + the repository working tree and writes deterministic generated
 * outputs (to gitignored locations such as `api/data/`). The orchestrator then
 * hands off to the web build, which prerenders the Static Mirror into
 * `web/dist/`. See architecture.md §AR-9 and §Infrastructure-Deployment.
 *
 * WHAT THIS STORY DELIVERS (the FOUNDATION, not the generators)
 * ------------------------------------------------------------
 * The registry is EMPTY now. Story 1.8 ships the SCAFFOLD — this orchestrator,
 * the `content/` source-of-truth dir, the `pnpm build` wiring, the determinism
 * guarantee, and the extension hooks. The first real generators plug into the
 * registry later:
 *   - Story 2.1 — render-glassbox  (AR-13 publish allowlist → Glass Box reader data)
 *   - Story 4.1 — build-kb-index   (content/kb/*.md → Orama index → api/data/)
 * Because the registry is empty, this runs as a clean NO-OP today: `pnpm build`
 * produces a byte-identical `web/dist/` to a plain `astro build` (the pipeline
 * generates nothing yet). That additive-no-op property is the byte-stability
 * baseline the determinism check (`check-deterministic.ts`) and the lead's smoke
 * gate verify.
 *
 * HARD CONSTRAINTS (FR-33 / NFR-6 — code-as-CMS, deterministic regeneration)
 * -------------------------------------------------------------------------
 *  - NO network reads, ever. No fetch, no HTTP client, and no reads from GitHub,
 *    YouTube, or Suno. The repo is the single source of truth; curated media is
 *    committed into `content/`. (Verified by the orchestrator unit test, which
 *    asserts this file contains no network primitive.)
 *  - NO admin / CMS surface. The site is pure static (`web/dist/`) + the later
 *    Hono api; content is edited as code in `content/` and regenerated by this
 *    pipeline. There is nothing to administer at runtime.
 *  - DETERMINISTIC. No `Date.now()`, no `Math.random()`, no argless `new Date()`
 *    may influence output. Any directory/glob enumeration MUST be sorted
 *    (filesystem order is not guaranteed across machines). If a generator ever
 *    needs a timestamp, derive it from git — the committer date of the source
 *    file — exactly as `web/src/lib/lastmod.ts` does (Story 1.6). Same git
 *    state → byte-identical output.
 *
 * RUNTIME: executes in Node via `tsx` (the repo's `.ts`-script convention; see
 * the api's `tsx` usage). It is never shipped to the browser.
 */
import { fileURLToPath } from 'node:url';

import { buildEpkGenerator } from './build-epk.ts';
import { buildKbIndexGenerator } from './build-kb-index.ts';
import { harvestTimelineGenerator } from './harvest-timeline.ts';
import { renderGlassboxGenerator } from './render-glassbox.ts';

/**
 * A single content generator: a named, deterministic step that reads only from
 * `content/` + the repo and writes generated outputs to gitignored locations.
 * The orchestrator runs the registry in array order and logs each step.
 *
 * Generators are intentionally async — the real ones (KB index build, Glass Box
 * render) do file IO — but they MUST NOT perform any network IO.
 */
export interface Generator {
  /** Short, stable name used in the build log (e.g. "render-glassbox"). */
  readonly name: string;
  /** Run the generator. Throw to fail the build loudly (never swallow errors). */
  run(): Promise<void>;
}

/**
 * The ORDERED content-generator registry. EMPTY in Story 1.8 by design (this
 * story ships the scaffold + hooks, not the generators — skill-rules Rule 1
 * "no consumers yet"). Generators are added here, in dependency order, by:
 *
 *   // TODO(Story 2.1): render-glassbox generator (AR-13 allowlist → Glass Box data)
 *   // TODO(Story 4.1): build-kb-index generator (content/kb/*.md → Orama index → api/data/)
 *
 * Keep this array the single ordered source of truth for the pipeline. Each
 * entry MUST honor the HARD CONSTRAINTS above (no network, deterministic,
 * sorted enumeration). Adding an entry is the ONLY change needed to wire a new
 * generator into `pnpm build`.
 */
export const CONTENT_GENERATORS: readonly Generator[] = [
  // Story 2.1: publish allowlist + Glass Box render pipeline (AR-13).
  // Reads content/glassbox.allowlist.ts → writes web/src/generated/glassbox.json.
  renderGlassboxGenerator,
  // Story 6.1: deterministic git→Dot auto-harvest (FR-17).
  // Reads content/timeline.allowlist.ts + _bmad-output/ artifacts (via allowlist only)
  // → merges with TIMELINE_SEED curated seed → writes web/src/generated/timeline.json.
  // Replaces Stage-1 renderTimelineGenerator (hand-curated only).
  harvestTimelineGenerator,
  // Story 4.1: build-kb-index generator (content/kb/*.md → Orama corpus → api/data/).
  // Reads content/kb/*.md (default-deny, sorted) → chunks at heading boundaries →
  // writes api/data/kb-index.json (gitignored, deterministic chunk corpus).
  buildKbIndexGenerator,
  // Story 9.3: EPK PDF generator (web/src/data/speaking.ts → web/public/epk/...pdf).
  // Reads PERSON, BIOS, SIGNATURE_TALKS, REEL from speaking.ts → emits a 1–2 page
  // deterministic EPK PDF (pinned CreationDate/ID; no new Date()).
  buildEpkGenerator,
];

/** Options for {@link runPipeline} (a logger seam keeps it unit-testable). */
export interface RunPipelineOptions {
  /** Generators to run; defaults to the real {@link CONTENT_GENERATORS}. */
  generators?: readonly Generator[];
  /** Log sink; defaults to `console.log`. Injected in tests to capture output. */
  log?: (message: string) => void;
}

/**
 * Run the content pipeline: execute each generator in registry order, logging
 * what it runs so the build is observable. No-op-safe — with the empty registry
 * it logs start/0-generators/done and resolves without touching the filesystem.
 * A throwing generator propagates (fails the build); nothing is swallowed.
 */
export async function runPipeline(options: RunPipelineOptions = {}): Promise<void> {
  const generators = options.generators ?? CONTENT_GENERATORS;
  const log = options.log ?? ((message: string) => console.log(message));

  log(`[content-pipeline] starting — ${generators.length} generator(s) registered`);

  if (generators.length === 0) {
    // No generators registered (the Story 1.8 no-op state; Story 2.1 / 4.1 add entries).
    log('[content-pipeline] no generators registered yet — nothing to generate (no-op).');
  }

  for (let i = 0; i < generators.length; i++) {
    const generator = generators[i]!;
    log(`[content-pipeline] (${i + 1}/${generators.length}) running: ${generator.name}`);
    await generator.run();
    log(`[content-pipeline] (${i + 1}/${generators.length}) done: ${generator.name}`);
  }

  log('[content-pipeline] complete.');
}

/**
 * Is this module the process entry point (run as `tsx scripts/build-content.ts`)?
 * Compares the resolved module path to argv[1] so importing it in a test does
 * NOT execute the pipeline (the test imports `runPipeline` directly).
 */
function isMain(): boolean {
  const entry = process.argv[1];
  if (!entry) return false;
  return fileURLToPath(import.meta.url) === entry;
}

if (isMain()) {
  runPipeline().catch((error: unknown) => {
    console.error('[content-pipeline] FAILED:', error);
    process.exitCode = 1;
  });
}
